/* TA-LIB Copyright (c) 1999-2008, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* List of contributors:
 *
 *  Initial  Name/description
 *  -------------------------------------------------------------------
 *  MF       Mario Fortier (Replace when you are the original author)
 *
 * Change history:
 *
 *  MMDDYY BY     Description
 *  -------------------------------------------------------------------
 *  XXXXXX MF     Initial Version
 */

/**** START GENCODE SECTION 1 - DO NOT DELETE THIS LINE ****/
/* All code within this section is automatically
 * generated by gen_code. Any modification will be lost
 * next time gen_code is run.
 */
/* Generated */ 
/* Generated */ #if defined( _MANAGED )
/* Generated */    #include "TA-Lib-Core.h"
/* Generated */    #define TA_INTERNAL_ERROR(Id) (RetCode::InternalError)
/* Generated */    namespace TicTacTec { namespace TA { namespace Library {
/* Generated */ #elif defined( _JAVA )
/* Generated */    #include "ta_defs.h"
/* Generated */    #include "ta_java_defs.h"
/* Generated */    #define TA_INTERNAL_ERROR(Id) (RetCode.InternalError)
/* Generated */ #else
/* Generated */    #include <string.h>
/* Generated */    #include <math.h>
/* Generated */    #include "ta_func.h"
/* Generated */ #endif
/* Generated */ 
/* Generated */ #ifndef TA_UTILITY_H
/* Generated */    #include "ta_utility.h"
/* Generated */ #endif
/* Generated */ 
/* Generated */ #ifndef TA_MEMORY_H
/* Generated */    #include "ta_memory.h"
/* Generated */ #endif
/* Generated */ 
/* Generated */ #define TA_PREFIX(x) TA_##x
/* Generated */ #define INPUT_TYPE   double
/* Generated */ 
/* Generated */ #if defined( _MANAGED )
/* Generated */ int Core::StochRsiTvLookback( int           optInRSIPeriod, /* From 1 to 100000 */
/* Generated */                             int           optInStochasticPeriod, /* From 1 to 100000 */
/* Generated */                             int           optInSmoothK_Period, /* From 1 to 100000 */
/* Generated */                             int           optInSmoothD_Period, /* From 1 to 100000 */
/* Generated */                             MAType        optInSmooth_MAType ) /* Generated */ 
/* Generated */ #elif defined( _JAVA )
/* Generated */ public int stochRsiTvLookback( int           optInRSIPeriod, /* From 1 to 100000 */
/* Generated */                              int           optInStochasticPeriod, /* From 1 to 100000 */
/* Generated */                              int           optInSmoothK_Period, /* From 1 to 100000 */
/* Generated */                              int           optInSmoothD_Period, /* From 1 to 100000 */
/* Generated */                              MAType        optInSmooth_MAType ) /* Generated */ 
/* Generated */ #else
/* Generated */ TA_LIB_API int TA_STOCHRSITV_Lookback( int           optInRSIPeriod, /* From 1 to 100000 */
/* Generated */                                                 int           optInStochasticPeriod, /* From 1 to 100000 */
/* Generated */                                                 int           optInSmoothK_Period, /* From 1 to 100000 */
/* Generated */                                                 int           optInSmoothD_Period, /* From 1 to 100000 */
/* Generated */                                                 TA_MAType     optInSmooth_MAType ) /* Generated */ 
/* Generated */ #endif
/**** END GENCODE SECTION 1 - DO NOT DELETE THIS LINE ****/
{
   /* insert local variable here */
   int retValue;

/**** START GENCODE SECTION 2 - DO NOT DELETE THIS LINE ****/
/* Generated */ #ifndef TA_FUNC_NO_RANGE_CHECK
/* Generated */    /* min/max are checked for optInRSIPeriod. */
/* Generated */    if( (int)optInRSIPeriod == TA_INTEGER_DEFAULT )
/* Generated */       optInRSIPeriod = 3;
/* Generated */    else if( ((int)optInRSIPeriod < 1) || ((int)optInRSIPeriod > 100000) )
/* Generated */       return -1;
/* Generated */ 
/* Generated */    /* min/max are checked for optInStochasticPeriod. */
/* Generated */    if( (int)optInStochasticPeriod == TA_INTEGER_DEFAULT )
/* Generated */       optInStochasticPeriod = 3;
/* Generated */    else if( ((int)optInStochasticPeriod < 1) || ((int)optInStochasticPeriod > 100000) )
/* Generated */       return -1;
/* Generated */ 
/* Generated */    /* min/max are checked for optInSmoothK_Period. */
/* Generated */    if( (int)optInSmoothK_Period == TA_INTEGER_DEFAULT )
/* Generated */       optInSmoothK_Period = 3;
/* Generated */    else if( ((int)optInSmoothK_Period < 1) || ((int)optInSmoothK_Period > 100000) )
/* Generated */       return -1;
/* Generated */ 
/* Generated */    /* min/max are checked for optInSmoothD_Period. */
/* Generated */    if( (int)optInSmoothD_Period == TA_INTEGER_DEFAULT )
/* Generated */       optInSmoothD_Period = 3;
/* Generated */    else if( ((int)optInSmoothD_Period < 1) || ((int)optInSmoothD_Period > 100000) )
/* Generated */       return -1;
/* Generated */ 
/* Generated */    #if !defined(_MANAGED) && !defined(_JAVA)
/* Generated */    if( (int)optInSmooth_MAType == TA_INTEGER_DEFAULT )
/* Generated */       optInSmooth_MAType = (TA_MAType)0;
/* Generated */    else if( ((int)optInSmooth_MAType < 0) || ((int)optInSmooth_MAType > 8) )
/* Generated */       return -1;
/* Generated */ 
/* Generated */    #endif /* !defined(_MANAGED) && !defined(_JAVA)*/
/* Generated */ #endif /* TA_FUNC_NO_RANGE_CHECK */
/**** END GENCODE SECTION 2 - DO NOT DELETE THIS LINE ****/

   /* insert lookback code here. */

         
   retValue = LOOKBACK_CALL(RSI)( optInRSIPeriod );
   retValue += LOOKBACK_CALL(STOCHF)( optInStochasticPeriod, optInSmoothD_Period, optInSmooth_MAType );
   retValue += LOOKBACK_CALL(MA)( optInSmoothK_Period, optInSmooth_MAType );

   return retValue;
}

/**** START GENCODE SECTION 3 - DO NOT DELETE THIS LINE ****/
/*
 * TA_STOCHRSITV - TradingView Stochastic Relative Strength Index
 * 
 * Input  = double
 * Output = double, double
 * 
 * Optional Parameters
 * -------------------
 * optInRSIPeriod:(From 1 to 100000)
 *    RSI Period 
 * 
 * optInStochasticPeriod:(From 1 to 100000)
 *    Stochastic Period
 * 
 * optInSmoothK_Period:(From 1 to 100000)
 *    Smoothing for making the K line. Usually set to 3
 * 
 * optInSmoothD_Period:(From 1 to 100000)
 *    Smoothing for making the D line. Usually set to 3
 * 
 * optInSmooth_MAType:
 *    Type of smoothing Moving Average
 * 
 * 
 */
/* Generated */ 
/* Generated */ #if defined( _MANAGED ) && defined( USE_SUBARRAY )
/* Generated */ enum class Core::RetCode Core::StochRsiTv( int    startIdx,
/* Generated */                                            int    endIdx,
/* Generated */                                            SubArray<double>^ inReal,
/* Generated */                                            int           optInRSIPeriod, /* From 1 to 100000 */
/* Generated */                                            int           optInStochasticPeriod, /* From 1 to 100000 */
/* Generated */                                            int           optInSmoothK_Period, /* From 1 to 100000 */
/* Generated */                                            int           optInSmoothD_Period, /* From 1 to 100000 */
/* Generated */                                            MAType        optInSmooth_MAType,
/* Generated */                                            [Out]int%    outBegIdx,
/* Generated */                                            [Out]int%    outNBElement,
/* Generated */                                            SubArray<double>^  outK,
/* Generated */                                            SubArray<double>^  outD )
/* Generated */ #elif defined( _MANAGED )
/* Generated */ enum class Core::RetCode Core::StochRsiTv( int    startIdx,
/* Generated */                                            int    endIdx,
/* Generated */                                            cli::array<double>^ inReal,
/* Generated */                                            int           optInRSIPeriod, /* From 1 to 100000 */
/* Generated */                                            int           optInStochasticPeriod, /* From 1 to 100000 */
/* Generated */                                            int           optInSmoothK_Period, /* From 1 to 100000 */
/* Generated */                                            int           optInSmoothD_Period, /* From 1 to 100000 */
/* Generated */                                            MAType        optInSmooth_MAType,
/* Generated */                                            [Out]int%    outBegIdx,
/* Generated */                                            [Out]int%    outNBElement,
/* Generated */                                            cli::array<double>^  outK,
/* Generated */                                            cli::array<double>^  outD )
/* Generated */ #elif defined( _JAVA )
/* Generated */ public RetCode stochRsiTv( int    startIdx,
/* Generated */                            int    endIdx,
/* Generated */                            double       inReal[],
/* Generated */                            int           optInRSIPeriod, /* From 1 to 100000 */
/* Generated */                            int           optInStochasticPeriod, /* From 1 to 100000 */
/* Generated */                            int           optInSmoothK_Period, /* From 1 to 100000 */
/* Generated */                            int           optInSmoothD_Period, /* From 1 to 100000 */
/* Generated */                            MAType        optInSmooth_MAType,
/* Generated */                            MInteger     outBegIdx,
/* Generated */                            MInteger     outNBElement,
/* Generated */                            double        outK[],
/* Generated */                            double        outD[] )
/* Generated */ #else
/* Generated */ TA_LIB_API TA_RetCode TA_STOCHRSITV( int    startIdx,
/* Generated */                                      int    endIdx,
/* Generated */                                                 const double inReal[],
/* Generated */                                                 int           optInRSIPeriod, /* From 1 to 100000 */
/* Generated */                                                 int           optInStochasticPeriod, /* From 1 to 100000 */
/* Generated */                                                 int           optInSmoothK_Period, /* From 1 to 100000 */
/* Generated */                                                 int           optInSmoothD_Period, /* From 1 to 100000 */
/* Generated */                                                 TA_MAType     optInSmooth_MAType,
/* Generated */                                                 int          *outBegIdx,
/* Generated */                                                 int          *outNBElement,
/* Generated */                                                 double        outK[],
/* Generated */                                                 double        outD[] )
/* Generated */ #endif
/**** END GENCODE SECTION 3 - DO NOT DELETE THIS LINE ****/
{
   /* insert local variable here */
   ARRAY_REF(tempBuffer);

   ENUM_DECLARATION(RetCode) retCode;
   int lookbackTotal, lookbackSTOCHF, lookbackRSI, lookbackMA, tempArraySize;
   VALUE_HANDLE_INT(outBegIdx1);
   VALUE_HANDLE_INT(outBegIdx2);
   VALUE_HANDLE_INT(outNbElement1);

/**** START GENCODE SECTION 4 - DO NOT DELETE THIS LINE ****/
/* Generated */ 
/* Generated */ #ifndef TA_FUNC_NO_RANGE_CHECK
/* Generated */ 
/* Generated */    /* Validate the requested output range. */
/* Generated */    if( startIdx < 0 )
/* Generated */       return ENUM_VALUE(RetCode,TA_OUT_OF_RANGE_START_INDEX,OutOfRangeStartIndex);
/* Generated */    if( (endIdx < 0) || (endIdx < startIdx))
/* Generated */       return ENUM_VALUE(RetCode,TA_OUT_OF_RANGE_END_INDEX,OutOfRangeEndIndex);
/* Generated */ 
/* Generated */    #if !defined(_JAVA)
/* Generated */    if( !inReal ) return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */    #endif /* !defined(_JAVA)*/
/* Generated */    /* min/max are checked for optInRSIPeriod. */
/* Generated */    if( (int)optInRSIPeriod == TA_INTEGER_DEFAULT )
/* Generated */       optInRSIPeriod = 3;
/* Generated */    else if( ((int)optInRSIPeriod < 1) || ((int)optInRSIPeriod > 100000) )
/* Generated */       return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */ 
/* Generated */    /* min/max are checked for optInStochasticPeriod. */
/* Generated */    if( (int)optInStochasticPeriod == TA_INTEGER_DEFAULT )
/* Generated */       optInStochasticPeriod = 3;
/* Generated */    else if( ((int)optInStochasticPeriod < 1) || ((int)optInStochasticPeriod > 100000) )
/* Generated */       return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */ 
/* Generated */    /* min/max are checked for optInSmoothK_Period. */
/* Generated */    if( (int)optInSmoothK_Period == TA_INTEGER_DEFAULT )
/* Generated */       optInSmoothK_Period = 3;
/* Generated */    else if( ((int)optInSmoothK_Period < 1) || ((int)optInSmoothK_Period > 100000) )
/* Generated */       return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */ 
/* Generated */    /* min/max are checked for optInSmoothD_Period. */
/* Generated */    if( (int)optInSmoothD_Period == TA_INTEGER_DEFAULT )
/* Generated */       optInSmoothD_Period = 3;
/* Generated */    else if( ((int)optInSmoothD_Period < 1) || ((int)optInSmoothD_Period > 100000) )
/* Generated */       return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */ 
/* Generated */    #if !defined(_MANAGED) && !defined(_JAVA)
/* Generated */    if( (int)optInSmooth_MAType == TA_INTEGER_DEFAULT )
/* Generated */       optInSmooth_MAType = (TA_MAType)0;
/* Generated */    else if( ((int)optInSmooth_MAType < 0) || ((int)optInSmooth_MAType > 8) )
/* Generated */       return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */ 
/* Generated */    #endif /* !defined(_MANAGED) && !defined(_JAVA)*/
/* Generated */    #if !defined(_JAVA)
/* Generated */    if( !outK )
/* Generated */       return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */ 
/* Generated */    if( !outD )
/* Generated */       return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */ 
/* Generated */    #endif /* !defined(_JAVA) */
/* Generated */ #endif /* TA_FUNC_NO_RANGE_CHECK */
/* Generated */ 
/**** END GENCODE SECTION 4 - DO NOT DELETE THIS LINE ****/

   /* Insert TA function code here. */

   /* Default return values */
   VALUE_HANDLE_DEREF_TO_ZERO(outBegIdx);
   VALUE_HANDLE_DEREF_TO_ZERO(outNBElement);

   /* Adjust startIdx to account for the lookback period. */
   lookbackRSI = LOOKBACK_CALL(RSI)( optInRSIPeriod );
   lookbackSTOCHF = LOOKBACK_CALL(STOCHF)( optInStochasticPeriod, optInSmoothD_Period, optInSmooth_MAType );
   lookbackMA = LOOKBACK_CALL(MA)( optInSmoothK_Period, optInSmooth_MAType );

   lookbackTotal   = lookbackRSI + lookbackSTOCHF + lookbackMA;

   if( startIdx < lookbackTotal )
      startIdx = lookbackTotal;

   /* Make sure there is still something to evaluate. */
   if( startIdx > endIdx )
   {
      VALUE_HANDLE_DEREF_TO_ZERO(outBegIdx);
      VALUE_HANDLE_DEREF_TO_ZERO(outNBElement);
      return ENUM_VALUE(RetCode,TA_SUCCESS,Success);
   }

   VALUE_HANDLE_DEREF(outBegIdx) = startIdx;

   tempArraySize = (endIdx - startIdx) + 1 + lookbackSTOCHF;

   ARRAY_ALLOC( tempBuffer, tempArraySize );

   retCode = FUNCTION_CALL(RSI)(startIdx-lookbackSTOCHF, 
                                endIdx, 
                                inReal, 
                                optInRSIPeriod, 
                                VALUE_HANDLE_OUT(outBegIdx1),
                                VALUE_HANDLE_OUT(outNbElement1), 
                                tempBuffer);

   if( retCode != ENUM_VALUE(RetCode,TA_SUCCESS,Success) || VALUE_HANDLE_GET(outNbElement1) == 0 )
   {
      ARRAY_FREE( tempBuffer );
      VALUE_HANDLE_DEREF_TO_ZERO(outBegIdx);
      VALUE_HANDLE_DEREF_TO_ZERO(outNBElement);
      return retCode;
   }
   
   retCode = FUNCTION_CALL_DOUBLE(STOCHF)(0,
                                          tempArraySize-1,
                                          tempBuffer,
                                          tempBuffer,
                                          tempBuffer,
                                          optInStochasticPeriod,
                                          optInSmoothK_Period,
                                          optInSmooth_MAType,
                                          VALUE_HANDLE_OUT(outBegIdx2),
                                          outNBElement,
                                          outK,
                                          tempBuffer);
   
    if( retCode != ENUM_VALUE(RetCode,TA_SUCCESS,Success) || VALUE_HANDLE_GET(outNbElement1) == 0 )
   {
      ARRAY_FREE( tempBuffer );
      VALUE_HANDLE_DEREF_TO_ZERO(outBegIdx);
      VALUE_HANDLE_DEREF_TO_ZERO(outNBElement);
      return retCode;
   }
   
   retCode = FUNCTION_CALL_DOUBLE(MA)(0,
                                          tempArraySize-1,
                                          tempBuffer,
                                          optInSmoothD_Period,
                                          optInSmooth_MAType,
                                          VALUE_HANDLE_OUT(outBegIdx2),
                                          outNBElement,
                                          outD);

   ARRAY_FREE( tempBuffer );

   if( retCode != ENUM_VALUE(RetCode,TA_SUCCESS,Success) || ((int)VALUE_HANDLE_DEREF(outNBElement)) == 0 )
   {
      VALUE_HANDLE_DEREF_TO_ZERO(outBegIdx);
      VALUE_HANDLE_DEREF_TO_ZERO(outNBElement);
      return retCode;
   }

   return ENUM_VALUE(RetCode,TA_SUCCESS,Success);
}

/**** START GENCODE SECTION 5 - DO NOT DELETE THIS LINE ****/
/* Generated */ 
/* Generated */ #define  USE_SINGLE_PRECISION_INPUT
/* Generated */ #undef  TA_LIB_PRO
/* Generated */ #if !defined( _MANAGED ) && !defined( _JAVA )
/* Generated */    #undef   TA_PREFIX
/* Generated */    #define  TA_PREFIX(x) TA_S_##x
/* Generated */ #endif
/* Generated */ #undef   INPUT_TYPE
/* Generated */ #define  INPUT_TYPE float
/* Generated */ #if defined( _MANAGED ) && defined( USE_SUBARRAY )
/* Generated */ enum class Core::RetCode Core::StochRsiTv( int    startIdx,
/* Generated */                                            int    endIdx,
/* Generated */                                            SubArray<float>^ inReal,
/* Generated */                                            int           optInRSIPeriod, /* From 1 to 100000 */
/* Generated */                                            int           optInStochasticPeriod, /* From 1 to 100000 */
/* Generated */                                            int           optInSmoothK_Period, /* From 1 to 100000 */
/* Generated */                                            int           optInSmoothD_Period, /* From 1 to 100000 */
/* Generated */                                            MAType        optInSmooth_MAType,
/* Generated */                                            [Out]int%    outBegIdx,
/* Generated */                                            [Out]int%    outNBElement,
/* Generated */                                            SubArray<double>^  outK,
/* Generated */                                            SubArray<double>^  outD )
/* Generated */ #elif defined( _MANAGED )
/* Generated */ enum class Core::RetCode Core::StochRsiTv( int    startIdx,
/* Generated */                                            int    endIdx,
/* Generated */                                            cli::array<float>^ inReal,
/* Generated */                                            int           optInRSIPeriod, /* From 1 to 100000 */
/* Generated */                                            int           optInStochasticPeriod, /* From 1 to 100000 */
/* Generated */                                            int           optInSmoothK_Period, /* From 1 to 100000 */
/* Generated */                                            int           optInSmoothD_Period, /* From 1 to 100000 */
/* Generated */                                            MAType        optInSmooth_MAType,
/* Generated */                                            [Out]int%    outBegIdx,
/* Generated */                                            [Out]int%    outNBElement,
/* Generated */                                            cli::array<double>^  outK,
/* Generated */                                            cli::array<double>^  outD )
/* Generated */ #elif defined( _JAVA )
/* Generated */ public RetCode stochRsiTv( int    startIdx,
/* Generated */                            int    endIdx,
/* Generated */                            float        inReal[],
/* Generated */                            int           optInRSIPeriod, /* From 1 to 100000 */
/* Generated */                            int           optInStochasticPeriod, /* From 1 to 100000 */
/* Generated */                            int           optInSmoothK_Period, /* From 1 to 100000 */
/* Generated */                            int           optInSmoothD_Period, /* From 1 to 100000 */
/* Generated */                            MAType        optInSmooth_MAType,
/* Generated */                            MInteger     outBegIdx,
/* Generated */                            MInteger     outNBElement,
/* Generated */                            double        outK[],
/* Generated */                            double        outD[] )
/* Generated */ #else
/* Generated */ TA_RetCode TA_S_STOCHRSITV( int    startIdx,
/* Generated */                             int    endIdx,
/* Generated */                             const float  inReal[],
/* Generated */                             int           optInRSIPeriod, /* From 1 to 100000 */
/* Generated */                             int           optInStochasticPeriod, /* From 1 to 100000 */
/* Generated */                             int           optInSmoothK_Period, /* From 1 to 100000 */
/* Generated */                             int           optInSmoothD_Period, /* From 1 to 100000 */
/* Generated */                             TA_MAType     optInSmooth_MAType,
/* Generated */                             int          *outBegIdx,
/* Generated */                             int          *outNBElement,
/* Generated */                             double        outK[],
/* Generated */                             double        outD[] )
/* Generated */ #endif
/* Generated */ {
/* Generated */    ARRAY_REF(tempBuffer);
/* Generated */    ENUM_DECLARATION(RetCode) retCode;
/* Generated */    int lookbackTotal, lookbackSTOCHF, lookbackRSI, lookbackMA, tempArraySize;
/* Generated */    VALUE_HANDLE_INT(outBegIdx1);
/* Generated */    VALUE_HANDLE_INT(outBegIdx2);
/* Generated */    VALUE_HANDLE_INT(outNbElement1);
/* Generated */  #ifndef TA_FUNC_NO_RANGE_CHECK
/* Generated */     if( startIdx < 0 )
/* Generated */        return ENUM_VALUE(RetCode,TA_OUT_OF_RANGE_START_INDEX,OutOfRangeStartIndex);
/* Generated */     if( (endIdx < 0) || (endIdx < startIdx))
/* Generated */        return ENUM_VALUE(RetCode,TA_OUT_OF_RANGE_END_INDEX,OutOfRangeEndIndex);
/* Generated */     #if !defined(_JAVA)
/* Generated */     if( !inReal ) return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */     #endif 
/* Generated */     if( (int)optInRSIPeriod == TA_INTEGER_DEFAULT )
/* Generated */        optInRSIPeriod = 3;
/* Generated */     else if( ((int)optInRSIPeriod < 1) || ((int)optInRSIPeriod > 100000) )
/* Generated */        return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */     if( (int)optInStochasticPeriod == TA_INTEGER_DEFAULT )
/* Generated */        optInStochasticPeriod = 3;
/* Generated */     else if( ((int)optInStochasticPeriod < 1) || ((int)optInStochasticPeriod > 100000) )
/* Generated */        return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */     if( (int)optInSmoothK_Period == TA_INTEGER_DEFAULT )
/* Generated */        optInSmoothK_Period = 3;
/* Generated */     else if( ((int)optInSmoothK_Period < 1) || ((int)optInSmoothK_Period > 100000) )
/* Generated */        return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */     if( (int)optInSmoothD_Period == TA_INTEGER_DEFAULT )
/* Generated */        optInSmoothD_Period = 3;
/* Generated */     else if( ((int)optInSmoothD_Period < 1) || ((int)optInSmoothD_Period > 100000) )
/* Generated */        return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */     #if !defined(_MANAGED) && !defined(_JAVA)
/* Generated */     if( (int)optInSmooth_MAType == TA_INTEGER_DEFAULT )
/* Generated */        optInSmooth_MAType = (TA_MAType)0;
/* Generated */     else if( ((int)optInSmooth_MAType < 0) || ((int)optInSmooth_MAType > 8) )
/* Generated */        return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */     #endif 
/* Generated */     #if !defined(_JAVA)
/* Generated */     if( !outK )
/* Generated */        return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */     if( !outD )
/* Generated */        return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */     #endif 
/* Generated */  #endif 
/* Generated */    VALUE_HANDLE_DEREF_TO_ZERO(outBegIdx);
/* Generated */    VALUE_HANDLE_DEREF_TO_ZERO(outNBElement);
/* Generated */    lookbackRSI = LOOKBACK_CALL(RSI)( optInRSIPeriod );
/* Generated */    lookbackSTOCHF = LOOKBACK_CALL(STOCHF)( optInStochasticPeriod, optInSmoothD_Period, optInSmooth_MAType );
/* Generated */    lookbackMA = LOOKBACK_CALL(MA)( optInSmoothK_Period, optInSmooth_MAType );
/* Generated */    lookbackTotal   = lookbackRSI + lookbackSTOCHF + lookbackMA;
/* Generated */    if( startIdx < lookbackTotal )
/* Generated */       startIdx = lookbackTotal;
/* Generated */    if( startIdx > endIdx )
/* Generated */    {
/* Generated */       VALUE_HANDLE_DEREF_TO_ZERO(outBegIdx);
/* Generated */       VALUE_HANDLE_DEREF_TO_ZERO(outNBElement);
/* Generated */       return ENUM_VALUE(RetCode,TA_SUCCESS,Success);
/* Generated */    }
/* Generated */    VALUE_HANDLE_DEREF(outBegIdx) = startIdx;
/* Generated */    tempArraySize = (endIdx - startIdx) + 1 + lookbackSTOCHF;
/* Generated */    ARRAY_ALLOC( tempBuffer, tempArraySize );
/* Generated */    retCode = FUNCTION_CALL(RSI)(startIdx-lookbackSTOCHF, 
/* Generated */                                 endIdx, 
/* Generated */                                 inReal, 
/* Generated */                                 optInRSIPeriod, 
/* Generated */                                 VALUE_HANDLE_OUT(outBegIdx1),
/* Generated */                                 VALUE_HANDLE_OUT(outNbElement1), 
/* Generated */                                 tempBuffer);
/* Generated */    if( retCode != ENUM_VALUE(RetCode,TA_SUCCESS,Success) || VALUE_HANDLE_GET(outNbElement1) == 0 )
/* Generated */    {
/* Generated */       ARRAY_FREE( tempBuffer );
/* Generated */       VALUE_HANDLE_DEREF_TO_ZERO(outBegIdx);
/* Generated */       VALUE_HANDLE_DEREF_TO_ZERO(outNBElement);
/* Generated */       return retCode;
/* Generated */    }
/* Generated */    retCode = FUNCTION_CALL_DOUBLE(STOCHF)(0,
/* Generated */                                           tempArraySize-1,
/* Generated */                                           tempBuffer,
/* Generated */                                           tempBuffer,
/* Generated */                                           tempBuffer,
/* Generated */                                           optInStochasticPeriod,
/* Generated */                                           optInSmoothK_Period,
/* Generated */                                           optInSmooth_MAType,
/* Generated */                                           VALUE_HANDLE_OUT(outBegIdx2),
/* Generated */                                           outNBElement,
/* Generated */                                           outK,
/* Generated */                                           tempBuffer);
/* Generated */     if( retCode != ENUM_VALUE(RetCode,TA_SUCCESS,Success) || VALUE_HANDLE_GET(outNbElement1) == 0 )
/* Generated */    {
/* Generated */       ARRAY_FREE( tempBuffer );
/* Generated */       VALUE_HANDLE_DEREF_TO_ZERO(outBegIdx);
/* Generated */       VALUE_HANDLE_DEREF_TO_ZERO(outNBElement);
/* Generated */       return retCode;
/* Generated */    }
/* Generated */    retCode = FUNCTION_CALL_DOUBLE(MA)(0,
/* Generated */                                           tempArraySize-1,
/* Generated */                                           tempBuffer,
/* Generated */                                           optInSmoothD_Period,
/* Generated */                                           optInSmooth_MAType,
/* Generated */                                           VALUE_HANDLE_OUT(outBegIdx2),
/* Generated */                                           outNBElement,
/* Generated */                                           outD);
/* Generated */    ARRAY_FREE( tempBuffer );
/* Generated */    if( retCode != ENUM_VALUE(RetCode,TA_SUCCESS,Success) || ((int)VALUE_HANDLE_DEREF(outNBElement)) == 0 )
/* Generated */    {
/* Generated */       VALUE_HANDLE_DEREF_TO_ZERO(outBegIdx);
/* Generated */       VALUE_HANDLE_DEREF_TO_ZERO(outNBElement);
/* Generated */       return retCode;
/* Generated */    }
/* Generated */    return ENUM_VALUE(RetCode,TA_SUCCESS,Success);
/* Generated */ }
/* Generated */ 
/* Generated */ #if defined( _MANAGED )
/* Generated */ }}} // Close namespace TicTacTec.TA.Lib
/* Generated */ #endif
/**** END GENCODE SECTION 5 - DO NOT DELETE THIS LINE ****/

